CREATE TABLE `TEMAS` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`DESCRICAO` varchar(255) NOT NULL,
	`PESQUISA` varchar(255) NOT NULL,
	`DATA_INSERCAO` TIMESTAMP NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `POSTAGEM` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`TEMA_ID` bigint NOT NULL,
	`USUARIO_ID` bigint NOT NULL,
	`TITULO` varchar(255) NOT NULL,
	`TEXTO` varchar(3000) NOT NULL,
	`DATA` TIMESTAMP NOT NULL,
	`ATIVO` BOOLEAN NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USUARIO` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`USUARIO` varchar(255) NOT NULL,
	`SENHA` varchar(255) NOT NULL,
	`NOME` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `POSTAGEM` ADD CONSTRAINT `POSTAGEM_fk0` FOREIGN KEY (`TEMA_ID`) REFERENCES `TEMAS`(`ID`);

ALTER TABLE `POSTAGEM` ADD CONSTRAINT `POSTAGEM_fk1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`ID`);




